services:
  - type: web
    name: bias-detector-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /tmp/huggingface
    plan: free
